# Default values for dNiko-core-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-75224102aecc1abe7f723cc1c469f34c759a2ed5"
