# Default values for dNiko-core-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-f26715da7469c25be3087cf6ccef5da7da73e4c0"
