# Default values for dNiko-core-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-06080ffe1a4e1de1e3f3af3a5086aec8f7936973"
