apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dNiko-core-api.fullname" . }}-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.serviceConfig.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.serviceConfig.DB_PASSWORD | quote }}
