apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ShortLinks.fullname" . }}
  namespace: {{ include "ShortLinks.namespace" . }}
  labels:
    {{- include "ShortLinks.labels" . | nindent 4 }}
    {{- if .Values.labels}}
      {{ toYaml .Values.labels | nindent 8 }}
    {{- end}}
{{- if .Values.annotations }}
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "ShortLinks.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.annotations .Values.podMetadata.annotations }}
      annotations:
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podMetadata.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "ShortLinks.labels" . | nindent 8 }}
        {{- if .Values.podMetadata.labels}}
          {{ toYaml .Values.podMetadata.labels | nindent 8 }}
        {{- end}}
    spec:
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ include "ShortLinks.fullname" . }}-image-pull-secret
      {{- end }}
      serviceAccountName: {{ include "ShortLinks.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "ShortLinks.name" . }}-{{ .Values.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
