apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqz-page.fullname" . }}
  labels:
    {{- include "sqz-page.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sqz-page.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sqz-page.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ include "sqz-page.fullname" . }}-ghcr-creds
      {{- end }}
      serviceAccountName: {{ include "sqz-page.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "sqz-page.fullname" . }}-config
            - secretRef:
                name: {{ include "sqz-page.fullname" . }}-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/system/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/system/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
